In [108]:
import pandas as pd
import numpy as np
import sklearn as sk
pd.set_option('display.float_format', lambda x: '%.2f' % x)

# Pandas

In [65]:
#Pandas abc
df = pd.read_csv("../data/Salaries.csv",header=0,index_col="playerID",skiprows=[1])
df

yearID teamID lgID    salary
playerID                               
bedrost01    1985    ATL   NL    550000
benedbr01    1985    ATL   NL    545000
campri01     1985    ATL   NL    633333
ceronri01    1985    ATL   NL    625000
chambch01    1985    ATL   NL    800000
...           ...    ...  ...       ...
treinbl01    2015    WAS   NL    512800
ugglada01    2015    WAS   NL    507500
werthja01    2015    WAS   NL  21000000
zimmejo02    2015    WAS   NL  16500000
zimmery01    2015    WAS   NL  14000000

[25574 rows x 4 columns]

In [59]:
#Pandas d
df[(df['teamID'].isin(["ATL","HOU"])) & (df['salary']>1000000)]

yearID teamID lgID   salary
playerID                              
hornebo01    1985    ATL   NL  1500000
murphda05    1985    ATL   NL  1625000
suttebr01    1985    ATL   NL  1354167
ryanno01     1985    HOU   NL  1350000
hornebo01    1986    ATL   NL  1800000
...           ...    ...  ...      ...
quallch01    2015    HOU   AL  3000000
rasmuco01    2015    HOU   AL  8000000
singljo02    2015    HOU   AL  2000000
sippto01     2015    HOU   AL  2400000
valbulu01    2015    HOU   AL  4200000

[595 rows x 4 columns]

In [60]:
#Pandas e
df[df['teamID']=='ATL'].describe()

yearID      salary
count  885.00      885.00
mean  1999.73  2207749.19
std      8.77  3434319.61
min   1985.00    60000.00
25%   1992.00   300000.00
50%   1999.00   600000.00
75%   2007.00  2400000.00
max   2015.00 16061802.00

In [69]:
#Pandas f
dic={}
dic["playerID"]=[]
for i in df.columns.values:
    dic[i]=[]
it=df.iterrows()
for i in it:
    dic["playerID"].append(i[0])
    for (j,k) in enumerate(df.columns.values):
        dic[k].append(i[1][j])
        
dic

{'playerID': ['bedrost01',
  'benedbr01',
  'campri01',
  'ceronri01',
  'chambch01',
  'dedmoje01',
  'forstte01',
  'garbege01',
  'harpete01',
  'hornebo01',
  'hubbagl01',
  'mahleri01',
  'mcmurcr01',
  'mumphje01',
  'murphda05',
  'oberkke01',
  'perezpa01',
  'perryge01',
  'ramirra01',
  'suttebr01',
  'washicl01',
  'boddimi01',
  'dauerri01',
  'davisst02',
  'dempsri01',
  'dwyerji01',
  'flanami01',
  'fordda01',
  'grosswa01',
  'lacyle01',
  'lynnfr01',
  'martide01',
  'martiti01',
  'mcgresc01',
  'murraed02',
  'nolanjo01',
  'rayfofl01',
  'ripkeca01',
  'roeniga01',
  'sheetla01',
  'shelbjo01',
  'stewasa01',
  'youngmi01',
  'armasto01',
  'barrema02',
  'boggswa01',
  'bordiri01',
  'boydoi01',
  'bucknbi01',
  'clearma01',
  'clemero02',
  'crawfst01',
  'easlemi01',
  'evansdw01',
  'gedmari01',
  'gutieja01',
  'hoffmgl01',
  'hurstbr01',
  'juraked01',
  'kisonbr01',
  'milleri01',
  'nichore01',
  'nippeal01',
  'ojedabo01',
  'remyje01',
  'riceji01',
  'st

In [70]:
#Pandas g
df2=pd.DataFrame.from_dict(dic)
df2.columns=['a','b','c','d','e']
df2

a     b    c   d         e
0      bedrost01  1985  ATL  NL    550000
1      benedbr01  1985  ATL  NL    545000
2       campri01  1985  ATL  NL    633333
3      ceronri01  1985  ATL  NL    625000
4      chambch01  1985  ATL  NL    800000
...          ...   ...  ...  ..       ...
25569  treinbl01  2015  WAS  NL    512800
25570  ugglada01  2015  WAS  NL    507500
25571  werthja01  2015  WAS  NL  21000000
25572  zimmejo02  2015  WAS  NL  16500000
25573  zimmery01  2015  WAS  NL  14000000

[25574 rows x 5 columns]

# Numpy

In [84]:
# Numpy a
li = [[1,2],[3,4]]
arr = np.array(li)
arr

array([[1, 2],
       [3, 4]])

In [78]:
# Numpy b
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.data)

2
(2, 2)
4
int32
4


In [86]:
# Numpy c
arr = arr.flatten()
print(arr)
arr = arr.reshape([2,2])
print(arr)

[1 2 3 4]
[[1 2]
 [3 4]]


In [87]:
# Numpy d
arr[:,::-1]

array([[2, 1],
       [4, 3]])

In [104]:
# Numpy e
print(arr.argmin(axis=1))
print(arr.argmax())
print(arr.min())
print(arr.max())
print(arr.mean())
print(arr.sum())
print(arr.std())
print(np.dot(arr,arr))
print(arr**2)
print(arr**0.5)
print(np.abs(arr))
print(np.exp(arr))
print(np.sign(arr))
print(np.mod(arr,2))

[0 0]
3
1
4
2.5
10
1.118033988749895
[[ 7 10]
 [15 22]]
[[ 1  4]
 [ 9 16]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[1 2]
 [3 4]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
[[1 1]
 [1 1]]
[[1 0]
 [1 0]]


In [106]:
# Numpy f
print(np.arange(10))
print(np.ones((2,3)))
print(np.zeros((2,3)))
print(np.eye(3))
print(np.linspace(0,2,9))
print(np.concatenate((np.ones((2,2)),np.zeros((2,2))),axis=0))

[0 1 2 3 4 5 6 7 8 9]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]


# Scikit-Learn

In [ ]:
# Scikit-Learn a


# GitHub